import Link from "next/link"
import "./globals.css"

import { DM_Sans } from "next/font/google"
import { Inter } from "next/font/google"
import { ThemeProvider } from "@/components/theme-provider"
import { Analytics } from "@/components/analytics"
import { ModeToggle } from "@/components/mode-toggle"
import Image from "next/image"
import Footer from "@/components/Footer"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

interface RootLayoutProps {
  children: React.ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body
        className={`antialiased min-h-scree bg-white dark:bg-zinc-900 text-gray-800 dark:text-slate-50 ${inter.className}`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <div className="max-w-4xl mx-auto py-10 px-4">
            <header className="sticky top-0  main-header backdrop-blur-md bg-header py-3">

             
                <nav className=" py-2 mx-auto flex justify-between items-center ">

                <Link href="/" className=" hover:text-teal-500 hidden shrink-0 sm:block">
                  <Image 
                    src="/mj.png"
                    width={40}
                    height={40}
                    alt="emje"
                  />
                </Link>
                  <ul className="flex items-center gap-6 text-[0.875rem] font-medium">
                    <li><Link href="/" className=" hover:text-teal-500">Home</Link></li>
                    <li><Link href="/about" className=" hover:text-teal-500">About</Link></li>
                    <li><Link href="/case"className=" hover:text-teal-500">Case studies</Link></li>
                  </ul>
                 
                  <ModeToggle />
                  
           
             
                </nav>
        
            </header>
            <main>{children}</main>
            <Footer/>
          </div>
          <Analytics />
        </ThemeProvider>
      </body>

      
    </html>
  )
}
